# Generated by Django 4.2.11 on 2026-06-14 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='PWD Management System', max_length=200)),
                ('short_name', models.CharField(default='PWDMS', max_length=50)),
                ('district_name', models.CharField(default='', max_length=200)),
                ('region', models.CharField(default='', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logos/')),
                ('logo_secondary', models.ImageField(blank=True, null=True, upload_to='settings/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/icons/')),
                ('primary_color', models.CharField(default='#1a56db', help_text='Hex color', max_length=7)),
                ('secondary_color', models.CharField(default='#7e3af2', max_length=7)),
                ('accent_color', models.CharField(default='#ff5a1f', max_length=7)),
                ('text_on_primary', models.CharField(default='#ffffff', max_length=7)),
                ('footer_text', models.TextField(default='Ghana PWD Management System')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('album_title', models.CharField(default='PWD Directory', max_length=200)),
                ('album_subtitle', models.CharField(default='Registered Persons with Disability', max_length=300)),
                ('album_show_reg_number', models.BooleanField(default=True)),
                ('album_show_disability', models.BooleanField(default=True)),
                ('album_show_community', models.BooleanField(default=True)),
                ('album_show_phone', models.BooleanField(default=False)),
                ('album_photos_per_page', models.PositiveIntegerField(default=12)),
                ('album_header_color', models.CharField(default='#1a56db', max_length=7)),
                ('album_bg_color', models.CharField(default='#f9fafb', max_length=7)),
                ('notify_new_pwd', models.BooleanField(default=True)),
                ('notify_benefit_approval', models.BooleanField(default=True)),
                ('notify_complaint_assigned', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger'), ('new_pwd', 'New PWD Registered'), ('benefit', 'Benefit Update'), ('complaint', 'Complaint Update'), ('audit', 'Audit Alert'), ('system', 'System')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Frontend route', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
