# Generated by Django 4.2.11 on 2026-03-31 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pwds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_in_kind', models.CharField(blank=True, max_length=200)),
                ('frequency', models.CharField(choices=[('once', 'One-Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annual'), ('as_needed', 'As Needed')], max_length=20)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('pending', 'Pending')], default='active', max_length=20)),
                ('max_beneficiaries', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Benefit Categories',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('partner_type', models.CharField(choices=[('ngo', 'NGO'), ('government', 'Government Institution'), ('international', 'International Organization'), ('faith_based', 'Faith-Based Organization'), ('private', 'Private Sector')], max_length=30)),
                ('acronym', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/')),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField()),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('amount_disbursed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('in_kind_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('receipt_document', models.FileField(blank=True, null=True, upload_to='benefits/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_allocations', to=settings.AUTH_USER_MODEL)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='benefits.benefit')),
                ('pwd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_allocations', to='pwds.pwd')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-allocation_date'],
            },
        ),
        migrations.AddField(
            model_name='benefit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='benefits.benefitcategory'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='benefit',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='benefits.developmentpartner'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='target_disability_types',
            field=models.ManyToManyField(blank=True, to='pwds.disabilitytype'),
        ),
    ]
