# Generated by Django 4.2.11 on 2026-06-14 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('free', 'Free Trial'), ('starter', 'Starter'), ('standard', 'Standard'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Highlighted on pricing page')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('max_users', models.PositiveIntegerField(default=3, help_text='0 = unlimited')),
                ('max_pwds', models.PositiveIntegerField(default=50, help_text='0 = unlimited')),
                ('max_partners', models.PositiveIntegerField(default=2, help_text='0 = unlimited')),
                ('max_districts', models.PositiveIntegerField(default=1, help_text='0 = unlimited')),
                ('storage_gb', models.PositiveIntegerField(default=1, help_text='File/media storage in GB')),
                ('feature_ai', models.BooleanField(default=False, help_text='AI risk scoring & summaries')),
                ('feature_album_pdf', models.BooleanField(default=True, help_text='PDF album export')),
                ('feature_album_pptx', models.BooleanField(default=False, help_text='PowerPoint album export')),
                ('feature_audit', models.BooleanField(default=False, help_text='Full audit trail')),
                ('feature_reports', models.BooleanField(default=False, help_text='Advanced analytics & reports')),
                ('feature_api_access', models.BooleanField(default=False, help_text='REST API access')),
                ('feature_white_label', models.BooleanField(default=False, help_text='Custom branding / white-label')),
                ('feature_bulk_import', models.BooleanField(default=False, help_text='CSV bulk import')),
                ('feature_offline', models.BooleanField(default=True, help_text='Offline / PWA support')),
                ('feature_support', models.CharField(choices=[('community', 'Community'), ('email', 'Email'), ('priority', 'Priority'), ('dedicated', 'Dedicated')], default='community', help_text='Support tier', max_length=30)),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(help_text='District Assembly name', max_length=200)),
                ('tenant_email', models.EmailField(help_text='Billing contact email', max_length=254)),
                ('tenant_phone', models.CharField(blank=True, max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('trialing', 'Free Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='trialing', max_length=20)),
                ('trial_start', models.DateField(blank=True, null=True)),
                ('trial_end', models.DateField(blank=True, null=True)),
                ('current_period_start', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('manual', 'Manual')], max_length=30)),
                ('paystack_customer_id', models.CharField(blank=True, max_length=100)),
                ('paystack_subscription_id', models.CharField(blank=True, max_length=100)),
                ('last_payment_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], default='open', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('paystack_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='subscriptions.subscription')),
            ],
            options={
                'unique_together': {('subscription', 'feature', 'period_start')},
            },
        ),
    ]
