# Generated by Django 4.2.11 on 2026-03-31 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('physical', 'Physical'), ('sensory', 'Sensory'), ('intellectual', 'Intellectual'), ('psychosocial', 'Psychosocial'), ('multiple', 'Multiple')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PWD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registration_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pwds/photos/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('nationality', models.CharField(default='Ghanaian', max_length=50)),
                ('national_id', models.CharField(blank=True, help_text='Ghana Card / Passport / NHIS', max_length=50)),
                ('national_id_type', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('digital_address', models.CharField(blank=True, help_text='Ghana Post GPS', max_length=30)),
                ('house_number', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('community', models.CharField(max_length=100)),
                ('sub_district', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('education_level', models.CharField(choices=[('none', 'None'), ('primary', 'Primary'), ('jhs', 'JHS'), ('shs', 'SHS'), ('tertiary', 'Tertiary'), ('vocational', 'Vocational')], max_length=20)),
                ('employment_status', models.CharField(choices=[('unemployed', 'Unemployed'), ('employed', 'Employed'), ('self_employed', 'Self Employed'), ('student', 'Student'), ('retired', 'Retired')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('household_size', models.PositiveIntegerField(default=1)),
                ('caregiver_name', models.CharField(blank=True, max_length=200)),
                ('caregiver_phone', models.CharField(blank=True, max_length=20)),
                ('caregiver_relationship', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deceased', 'Deceased'), ('relocated', 'Relocated'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('ai_risk_score', models.FloatField(blank=True, help_text='AI-generated vulnerability score 0-100', null=True)),
                ('ai_risk_label', models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical')], max_length=20)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated profile summary')),
                ('ai_recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_pwds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PWD',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='PWDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('birth_cert', 'Birth Certificate'), ('national_id', 'National ID'), ('medical_report', 'Medical Report'), ('disability_cert', 'Disability Certificate'), ('photo', 'Photo'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='pwds/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('pwd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pwds.pwd')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('profound', 'Profound')], max_length=20)),
                ('disability_onset', models.CharField(choices=[('congenital', 'Congenital (From Birth)'), ('acquired', 'Acquired'), ('progressive', 'Progressive')], max_length=20)),
                ('onset_age', models.PositiveIntegerField(blank=True, help_text='Age when disability started', null=True)),
                ('cause_of_disability', models.TextField(blank=True)),
                ('has_assistive_device', models.BooleanField(default=False)),
                ('assistive_device_type', models.CharField(blank=True, max_length=200)),
                ('device_condition', models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('needed', 'Needed')], max_length=20)),
                ('current_medications', models.TextField(blank=True)),
                ('hospital_facility', models.CharField(blank=True, max_length=200)),
                ('last_medical_checkup', models.DateField(blank=True, null=True)),
                ('health_insurance', models.BooleanField(default=False)),
                ('nhis_number', models.CharField(blank=True, max_length=30)),
                ('additional_health_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disability_types', models.ManyToManyField(related_name='pwds', to='pwds.disabilitytype')),
                ('pwd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pwds.pwd')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
